on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dsherret/rust-toolchain-file@v1
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
      - name: Clippy check runtimelib with async-dispatcher-runtime
        run: cargo clippy -p runtimelib --all-targets --no-default-features --features "async-dispatcher-runtime,ring"
      - name: Clippy check runtimelib with tokio-runtime
        run: cargo clippy -p runtimelib --all-targets --no-default-features --features "tokio-runtime,ring"
      - name: Clippy check jupyter-serde, nbformat, and any other defaults
        run: cargo clippy --all-targets
